language: ruby
dist: xenial
addons:
  snaps:
    - name: helm
      classic: true

after_success:
  # Merge PRs or master branch updates into staging branch automatically
  - ./shared/update-staging.sh

branches:
  except:
    - flux-sync
    - flux-write-check
