apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: jupiter-brain-com
  namespace: macstadium-prod-1
  labels:
    chart: jupiter-brain
spec:
  chartGitPath: jupiter-brain
  releaseName: jupiter-brain-com
  values:
    trvs:
      enabled: true
      env: production-1
      pro: true
    honeycomb:
      dataset: jb-requests
      sampleRate: 10
