apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: vsphere-janitor-custom-5
  namespace: macstadium-prod-1
spec:
  chart:
    path: charts/vsphere-janitor
    git: git@github.com:travis-ci/kubernetes-config.git
  releaseName: vsphere-janitor-custom-5
  values:
    trvs:
      enabled: true
      env: custom-5-1
      pro: false
