apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: worker-org
  namespace: macstadium-prod-1
  labels:
    chart: macstadium-worker
spec:
  chartGitPath: macstadium-worker
  releaseName: worker-org
  values:
    image:
      tag: v5.0.0
    # Eventually this should be:
    # replicaCount: 8
    replicaCount: 1
    site: org

    concurrency:
      poolSize: 20
      totalJobs: 20 # eventually 160ish
      redis:
        name: worker-redis-master

    jupiterBrainName: jupiter-brain-org
    trvs:
      enabled: true
      app: macstadium-workers
      env: production-common
