apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: worker-custom-2
  namespace: macstadium-prod-1
spec:
  chart:
    path: charts/macstadium-worker
    git: git@github.com:travis-ci/kubernetes-config.git
  releaseName: worker-custom-2
  values:
    image:
      tag: v6.1.0
    replicaCount: 1
    site: com
    poolSize: 5
    jupiterBrainName: jupiter-brain-custom-2
    trvs:
      enabled: true
      app: macstadium-workers
      env: production-common
      pro: true
