apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: worker-org
  namespace: macstadium-prod-1
spec:
  chart:
    path: charts/macstadium-worker
    git: git@github.com:travis-ci/kubernetes-config.git
  releaseName: worker-org
  values:
    image:
      tag: v6.1.0
    # Eventually this should be:
    # replicaCount: 8
    replicaCount: 1
    site: org
    poolSize: 20
    jupiterBrainName: jupiter-brain-org
    trvs:
      enabled: true
      app: macstadium-workers
      env: production-common
