apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: worker-com
  namespace: gce-staging-1
spec:
  chart:
    path: charts/gce-worker
    git: git@github.com:travis-ci/kubernetes-config.git
    ref: staging
  releaseName: worker-com
  values:
    image:
      tag: v6.2.0

    cluster:
      enabled: true
      maxJobs: 8
      maxJobsPerWorker: 2

    site: com

    trvs:
      enabled: true
      app: gce-workers
      env: staging-1
      pro: true
