{{- if .Values.trvs.enabled }}
apiVersion: travisci.com/v1
kind: TrvsSecret
metadata:
  name: {{ include "vsphere-janitor.secret" . }}
  labels:
    app.kubernetes.io/name: {{ include "vsphere-janitor.name" . }}
    helm.sh/chart: {{ include "vsphere-janitor.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  app: {{ .Values.trvs.app }}
  env: {{ .Values.trvs.env }}
  prefix: VSPHERE_JANITOR
  pro: {{ .Values.trvs.pro }}
{{- end }}
