# Default values for macstadium-worker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: travisci/worker
  tag: v4.6.2
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

# Pull secrets from trvs keychain
trvs:
  # If not enabled, be sure to set secretName and create a secret with the
  # necessary environment variables for worker
  enabled: false
  app: ""  # Different infras use a different app key for their secrets
  env: ""
  pro: false

# Override the name of the secret with environment variables.
#
# If trvs.enabled is true, it will create a secret with this name instead
# of using the fullname of the deployment.
#
# If trvs.enabled is false, this should be set and you must create a secret
# with the given name that has the right environment variables.
secretName: ""

# Which travis-ci site this worker is for ("org" or "com")
site: ""

# How many concurrent jobs this worker can run
poolSize: 2

# The AMQP queue to pull jobs from
queue: builds.macstadium6

# The name of the jupiter-brain service/secret for the jupiter-brain to connect to
jupiterBrainName: ""

# The name of the secret that contains the Travis build VM SSH private key
#
# This secret must store the private key under the key "travis-vm-ssh-key" regardless
# of this value.
sshKeySecretName: "travis-vm-ssh-key"
