apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: jupiter-brain-com
  namespace: macstadium-staging
spec:
  chart:
    path: charts/jupiter-brain
    git: git@github.com:travis-ci/kubernetes-config.git
    ref: staging
  releaseName: jupiter-brain-com
  values:
    image:
      tag: v1.1.0-3-g9f47a0f
    trvs:
      enabled: true
      env: staging-1
      pro: true
    honeycomb:
      dataset: jb-requests-staging
