apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: vsphere-janitor
  namespace: macstadium-staging
spec:
  chart:
    path: charts/vsphere-janitor
    git: https://github.com/travis-ci/kubernetes-config.git
    ref: staging
  releaseName: vsphere-janitor
  values:
    trvs:
      enabled: true
      env: staging-1
