apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: worker-com
  namespace: macstadium-staging
  labels:
    chart: macstadium-worker
spec:
  chartGitPath: macstadium-worker
  releaseName: worker-com
  values:
    image:
      tag: v5.0.0
    replicaCount: 4
    site: com
    poolSize: 2
    jupiterBrainName: jupiter-brain-com
    trvs:
      enabled: true
      app: macstadium-workers
      env: staging-common
      pro: true
