apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: worker-org
  namespace: macstadium-staging
spec:
  chart:
    path: charts/macstadium-worker
    git: git@github.com:travis-ci/kubernetes-config.git
    ref: staging
  releaseName: worker-org
  values:
    image:
      tag: v5.0.0
    replicaCount: 4
    site: org
    poolSize: 2
    jupiterBrainName: jupiter-brain-org
    trvs:
      enabled: true
      app: macstadium-workers
      env: staging-common
