apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "backup.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "backup.name" . }}
    helm.sh/chart: {{ include "backup.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "backup.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.etcd.image.repository }}:{{ .Values.etcd.image.tag }}"
              imagePullPolicy: {{ .Values.etcd.image.pullPolicy }}
              env:
                - name: ETCDCTL_API
                  value: "3"
              command: ["/bin/sh"]
              args:
                - '-c'
                - >
                  etcdctl
                  --endpoints=127.0.0.1:2379
                  --cacert=/certs/ca.crt
                  --cert=/certs/healthcheck-client.crt
                  --key=/certs/healthcheck-client.key
                  snapshot save
                  /backup/etcd-snapshot-$(date +%Y-%m-%d_%H:%M:%S_%Z).db
              volumeMounts:
                - mountPath: /certs
                  name: etcd-certs
                  readOnly: true
                - mountPath: /backup
                  name: backup
              resources:
{{ toYaml .Values.resources | indent 16 }}
          hostNetwork: true
          restartPolicy: OnFailure
          volumes:
            - name: etcd-certs
              hostPath:
                path: /etc/kubernetes/pki/etcd
                type: Directory
            - name: backup
              hostPath:
                path: /backup
                type: DirectoryOrCreate
        {{- with .Values.nodeSelector }}
          nodeSelector:
{{ toYaml . | indent 12 }}
        {{- end }}
        {{- with .Values.affinity }}
          affinity:
{{ toYaml . | indent 12 }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
{{ toYaml . | indent 12 }}
        {{- end }}
